name: ParMOO CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run-full-tests:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.6", "3.10"]

    steps:
    - shell: bash
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: "${{matrix.python-version}}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f REQUIREMENTS ]; then pip install -r REQUIREMENTS; fi

    - name: Lint with flake8
      run: |
        cd tests
        ./run-tests.sh -c

    - name: Test with pytest
      run: |
        export PYTHONPATH=$PYTHONPATH:`pwd`
        cd tests
        ./run-tests.sh -ts
