name: ParMOO CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  run-full-tests:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.6", "3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: "${{matrix.python-version}}"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f REQUIREMENTS ]; then pip install -r REQUIREMENTS; fi

    - name: Lint with flake8
      shell: bash
      run: |
        cd tests
        ./run-tests.sh -c

    - name: Test with pytest
      shell: bash
      env:
        PYTHONPATH_PATH: $HOME
      run: |
        echo $HOME
        echo $PYTHONPATH
        cd tests
        ./run-tests.sh -ts
